#pragma once

typedef enum
{
    DEV_IRQ_CHANNEL_DEFAULT,
    DEV_IRQ_CHANNEL_L1SM,
    DEV_IRQ_CHANNEL_CTIRQ1,
    DEV_IRQ_CHANNEL_L1D_CTIRQ2,//FCCH relate
    DEV_IRQ_CHANNEL_L1D_DSP,
    DEV_IRQ_CHANNEL_USIM,
    DEV_IRQ_CHANNEL_DMA,
    DEV_IRQ_CHANNEL_UART1,
    DEV_IRQ_CHANNEL_KEYBOARD,
    DEV_IRQ_CHANNEL_UART2,
    DEV_IRQ_CHANNEL_GPT,
    DEV_IRQ_CHANNEL_EINT,
    DEV_IRQ_CHANNEL_USB,
    DEV_IRQ_CHANNEL_MSDC,
    DEV_IRQ_CHANNEL_RTC = 14,
    DEV_IRQ_CHANNEL_LCD = 16,
    DEV_IRQ_CHANNEL_UART3 = 17,
    DEV_IRQ_CHANNEL_AUDIO_DSP = 20,
    DEV_IRQ_CHANNEL_RESIZER = 21,
    DEV_IRQ_CHANNEL_I2C = 26,
    DEV_IRQ_CHANNEL_USIM2 = 28,
    DEV_IRQ_CHANNEL_TOUCHSCREEN = 31,
    DEV_IRQ_CHANNEL_ROTDMA = 33
} DEV_IRQ_CHANNEL;